### ISSUE TITLE
AUDIT 1 - Documents to Produce

### ISSUE THREAD

**Issue by chrisbodger** [chrisbodger/VeinCam#15]
- Differentiation document between Venenfinder and VeinCam
- Requirements Analysis
- ConOps Finalisation
- Decision Document
- Stakeholder Analysis

**Comment by chrisbodger** [comment]
Differentiation section has been added to the CONOPS. Can be moved out into a separate document should it be deemed necessary

**Comment by steph-pratt** [comment]
Stakeholder analysis and requirements draft has been added to google drive, need to be finalised and put on the GitHub
