### ISSUE TITLE
AUDIT 1 - Stakeholder Analysis

### ISSUE THREAD

**Issue by chrisbodger** [chrisbodger/VeinCam#18]
Comments left regarding Stakeholder Analysis
- Definition should focus on people or groups instead of Project. perhaps include patients and medical professionals/hospitals

**Comment by steph-pratt** [comment]
Now in the Google Drive, I am unsure how to add it into the GitHub as a word doc if someone could please do that (or show me). I also have it in two formats - as list and as a table - can look and see which is better

**Comment by JoeyMcP** [comment]
Added to ConOps under Stakeholders heading.
