### ISSUE TITLE
Agenda for tutorial week 4

### ISSUE THREAD

**Issue by steph-pratt** [chrisbodger/VeinCam#22]
Detailed agenda to be drafted, addressing all concerns mentioned in feedback as well as positive elements. This should be distributed before the tutorial. Chris? Joey?

**Comment by chrisbodger** [comment]
Yes, that way members of the tutorial will be aware of the topics covered in our meeting. Particularly if we are presenting an update for them.

**Comment by JoeyMcP** [comment]
Draft agenda up, add anything I missed from the feedback. No positive things on there yet.
