### ISSUE TITLE
Research into wavelengths of light

### ISSUE THREAD

**Issue by steph-pratt** [chrisbodger/VeinCam#23]
Ben mentioned in recent email we may want to add this to our area to research to help Alex and Chris select the best LEDs to employ. 

Links include:
- https://en.wikipedia.org/wiki/Near-infrared_window_in_biological_tissue
- https://en.wikipedia.org/wiki/Pulse_oximetry (although note we aren't trying to identify the difference between quantities of oxy and deoxy-haemoblobin with our device, so the difference in absorbance between these two wavelengths is a bit of a red hearing)
- https://www.slideshare.net/JefThomas1/vein-viewernir-imaging
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5822547/
- http://www.mdpi.com/1424-8220/17/2/304/htm
- https://onlinelibrary.wiley.com/doi/abs/10.1002/lsm.10248

Will discuss further at Wednesday meeting

**Comment by chrisbodger** [comment]
Paper confirmed 850nm is optimal. See issue [44](44).
